# Generated by Django 4.2 on 2023-04-21 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ttt_front', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_client', models.AutoField(primary_key=True, serialize=False)),
                ('adresse_client', models.CharField(blank=True, max_length=255, null=True)),
                ('mail_client', models.CharField(blank=True, max_length=50, null=True)),
                ('nom_client', models.CharField(blank=True, max_length=50, null=True)),
                ('suppr', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='EtatExemplaire',
            fields=[
                ('id_etat_exemplaire', models.AutoField(primary_key=True, serialize=False)),
                ('description_etat', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'etat_exemplaire',
            },
        ),
        migrations.CreateModel(
            name='Exemplaire',
            fields=[
                ('id_exemplaire', models.AutoField(primary_key=True, serialize=False)),
                ('numero_exemplaire', models.IntegerField(blank=True, null=True)),
                ('prix_vente_euros', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('vente_remboursee', models.BooleanField(default=False)),
                ('date_vente', models.DateField(blank=True, null=True)),
                ('localite_exemplaire', models.CharField(blank=True, max_length=150, null=True)),
                ('commentaire', models.CharField(blank=True, max_length=255, null=True)),
                ('montant_frais_de_port', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('frais_de_port_rembourses', models.BooleanField(default=False)),
                ('id_cassette', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ttt_front.cassette')),
                ('id_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ttt_back.client')),
                ('id_etat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ttt_back.etatexemplaire')),
                ('id_vendeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'exemplaire',
            },
        ),
    ]
