# Generated by Django 4.2 on 2023-05-06 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ttt_back', '0002_comptavendeur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exemplaire',
            old_name='id_etat',
            new_name='id_etat_exemplaire',
        ),
    ]
