# Generated by Django 4.2 on 2023-04-17 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttt_back', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='suppr',
            field=models.IntegerField(default=0),
        ),
    ]
