# Generated by Django 4.2 on 2023-04-19 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ttt_front', '0003_alter_artiste_image_artiste_alter_cassette_download_and_more'),
        ('ttt_back', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exemplaire',
            name='id_cassette',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ttt_front.cassette'),
        ),
    ]
