# Generated by Django 4.2 on 2023-04-18 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_a_recupere_user_a_rembourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='a_recupere',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='a_rembourse',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
    ]
