# Generated by Django 4.2 on 2023-04-22 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_user_a_recupere_remove_user_a_rembourse_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ComptaVendeur',
        ),
    ]
