# Generated by Django 4.2 on 2023-04-21 15:17

from django.db import migrations, models
import django_resized.forms
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cassette',
            fields=[
                ('id_cassette', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(blank=True, max_length=50, null=True)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('longueur', models.CharField(blank=True, max_length=10, null=True)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('lien_bandcamp', models.CharField(blank=True, max_length=255, null=True)),
                ('lien_soundcloud', models.CharField(blank=True, max_length=255, null=True)),
                ('lien_youtube', models.CharField(blank=True, max_length=255, null=True)),
                ('date_sortie', models.DateField(blank=True, null=True)),
                ('image_pochette', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=100, scale=0.5, size=[600, 600], upload_to='image_cassette')),
                ('download', models.FileField(blank=True, null=True, upload_to='file_cassette')),
                ('nombre_de_download', models.IntegerField(default=0)),
                ('prix', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('sold_out', models.BooleanField(default=False)),
                ('suppr', models.BooleanField(default=False)),
                ('publier', models.BooleanField(default=False)),
                ('nombre_exemplaire', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cassette',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id_event', models.AutoField(primary_key=True, serialize=False)),
                ('date_event', models.DateField(blank=True, null=True)),
                ('lieu', models.CharField(blank=True, max_length=255, null=True)),
                ('titre_event', models.CharField(blank=True, max_length=255, null=True)),
                ('description_event', tinymce.models.HTMLField(blank=True, null=True)),
                ('image_event', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=100, scale=0.5, size=[600, 600], upload_to='image_event')),
                ('suppr', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'event',
            },
        ),
        migrations.CreateModel(
            name='FraisDePort',
            fields=[
                ('id_frais_de_port', models.AutoField(primary_key=True, serialize=False)),
                ('nom_destination', models.CharField(blank=True, max_length=25, null=True)),
                ('montant_frais_de_port', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
            ],
            options={
                'db_table': 'frais_de_port',
            },
        ),
        migrations.CreateModel(
            name='Artiste',
            fields=[
                ('id_artiste', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=50, null=True)),
                ('image_artiste', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=100, scale=0.5, size=[600, 600], upload_to='image_artiste')),
                ('bio', tinymce.models.HTMLField(blank=True, null=True)),
                ('lien_artiste', models.CharField(blank=True, max_length=255, null=True)),
                ('suppr', models.BooleanField(default=False)),
                ('cassette', models.ManyToManyField(to='ttt_front.cassette', verbose_name='a produit')),
            ],
            options={
                'db_table': 'artiste',
            },
        ),
    ]
