# Generated by Django 4.2 on 2023-04-17 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttt_front', '0002_initial'),
    ]

    operations = []
