# Generated by Django 4.2 on 2023-04-29 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttt_front', '0002_alter_cassette_nombre_exemplaire_alter_cassette_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='artiste',
            name='publier',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='publier',
            field=models.BooleanField(default=False),
        ),
    ]
