# Generated by Django 4.2 on 2023-04-19 21:13

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('ttt_front', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artiste',
            name='image_artiste',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=100, scale=0.5, size=[600, 600], upload_to='image_artiste'),
        ),
        migrations.AlterField(
            model_name='cassette',
            name='download',
            field=models.FileField(blank=True, null=True, upload_to='file_cassette'),
        ),
        migrations.AlterField(
            model_name='cassette',
            name='image_pochette',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=100, scale=0.5, size=[600, 600], upload_to='image_cassette'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image_event',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=100, scale=0.5, size=[600, 600], upload_to='image_event'),
        ),
    ]
