# Generated by Django 4.2 on 2023-04-17 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttt_front', '0003_remove_event_suppr_remove_produire_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='suppr',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='artiste',
            name='suppr',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cassette',
            name='publier',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cassette',
            name='sold_out',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cassette',
            name='suppr',
            field=models.IntegerField(default=0),
        ),
    ]
