# Generated by Django 4.2 on 2023-04-17 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttt_front', '0004_event_suppr_alter_artiste_suppr_and_more'),
    ]

    operations = []
