# Generated by Django 4.2 on 2023-04-17 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttt_front', '0006_remove_produire_id_alter_artiste_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artiste',
            name='image_artiste',
            field=models.ImageField(null=True, upload_to='', verbose_name="image de l'artiste"),
        ),
        migrations.AlterField(
            model_name='cassette',
            name='image_pochette',
            field=models.ImageField(null=True, upload_to='', verbose_name='image de la pochette'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image_event',
            field=models.ImageField(null=True, upload_to='', verbose_name="image de l'event"),
        )
    ]
